name: Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
    - name: Test
      uses: ambersun1234/hardhat-test-action@v1
      with:
        network: hardhat