name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - additional-features

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install
        working-directory: smart-contract

      - name: Run tests
        working-directory: smart-contract
        run: npx hardhat test
